version: '3.6'

services:
  eureka-server:
    image: jakubkrhovjak/eureka-server
    ports:
     - "8761:8080"
    volumes:
     - .:/data
    network_mode: bridge

#  receive-service:
#    image: jakubkrhovjak/receiver-service
#    depends_on:
#      - eureka-server
#    ports:
#     - "8081:8080"
#    volumes:
#     - .:/data
#    network_mode: bridge
    command: /home/jakub/IdeaProjects/my-demos/spring-cloud-demo/wait.sh



#  feign-client:
#    image: jakubkrhovjak/feign-client
#    depends_on:doc
#      - postgres
#      - eureka-server
#      - receive-service
#    ports:
#     - "8082:8080"
#    volumes:
#     - .:/data
#    network_mode: bridge

  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:10.3-alpine
    volumes:
      - postgres-db:/var/lib/postgresql/datails\
    network_mode: bridge

volumes:
  postgres-db:
    external: true
